---
# tasks file for run

- name: install packages
  become: yes
  apt: name={{ item }} state=present
  with_items:
    - tomcat9

- name: sync-war-file
  synchronize:
    src: {{ src_folder }}
    dest: {{ dest_flder }}
    mode: push
  delegate_to: {{ delegate_serv }}

- name: start-tomcat
  systemd:
    name: tomcat9
    state: started
