---
# tasks file for run

- name: install packages
  become: yes
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - tomcat9

- name: sync-war-file
  synchronize:
    src: /usr/app/boxfuse-sample-java-war-hello/target/hello-1.0.war
    dest: /var/lib/tomcat9/webapps
    mode: push
  delegate_to: 34.118.83.252

- name: start-tomcat
  systemd:
    name: tomcat9
    state: started
